# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Jaccard subgroup similarity index
#'
#' @description
#' This function computes the Jaccard similarity index between two vectors of
#' subgroup membership labels, scaling it such that each leaf node contributes
#' equal weight to the overall similarity.
#'
#' @param x Numeric vector of subgroup memberships. Must be encoded as 
#'   integers, beginning at 0 and be contiguous (i.e., if there are k unique 
#'   values, they must be 0, 1, ..., k-1).
#' @param y Numeric vector of subgroup memberships Must be encoded as 
#'   integers, beginning at 0 and be contiguous (i.e., if there are k unique 
#'   values, they must be 0, 1, ..., k-1).
#'
#' @return Computed Jaccard subgroup similarity metric
#'
#' @export
jaccardSSI <- function(x, y) {
    .Call(`_causalDT_jaccardSSI`, x, y)
}

